In [1]:
import numpy as np

In [2]:
arr = np.array([10, 20, 30, 40, 50])
np.mean(arr) #Compute the mean (average) of an array

np.float64(30.0)

In [3]:
np.std(arr) # Compute the standard deviation of an array.

np.float64(14.142135623730951)

In [4]:
np.var(arr)  #Compute the minimum value of an array.

np.float64(200.0)

In [5]:
np.max(arr) #Compute the maximum value of an array.

np.int64(50)

In [6]:
np.min(arr) #Compute the minimum value of an array.

np.int64(10)

In [7]:
np.sum(arr) #Compute the sum of all elements in an array.

np.int64(150)

In [8]:
np.prod(arr)  #Compute the product of all elements in an array.

np.int64(12000000)

In [9]:
np.median(arr)  #Compute the median of an array.

np.float64(30.0)

In [10]:
np.percentile(arr, 50)  # For the 50th percentile (median)

np.float64(30.0)

In [11]:
np.argmin(arr) #Return the index of the minimum value in an array.

np.int64(0)

In [12]:
np.argmax(arr) #Return the index of the maxmium value in an array.

np.int64(4)

In [14]:
np.unique(arr)  #Find the unique elements of an array.

array([10, 20, 30, 40, 50])

In [15]:
np.diff(arr)  #Compute the n-th differences of an array

array([10, 10, 10, 10])

In [16]:
np.cumsum(arr)  #Compute the cumulative sum of an array.

array([ 10,  30,  60, 100, 150])

In [18]:
np.linspace(0, 10, 5)  # 5 numbers from 0 to 10

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [19]:
np.log(arr) #Compute natural log of an array

array([2.30258509, 2.99573227, 3.40119738, 3.68887945, 3.91202301])

In [20]:
np.exp(arr) #Compute exponential of an array

array([2.20264658e+04, 4.85165195e+08, 1.06864746e+13, 2.35385267e+17,
       5.18470553e+21])

In [21]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])
np.corrcoef(arr1, arr2)   #Compute the correlation coefficient matrix of two arrays

array([[1., 1.],
       [1., 1.]])

In [ ]:
#These methods are used for performing mathematical and statistical operations
#with NumPy.