### Why Python Lists are Slow for Numerical Computing

- Store elements as pointers instead of a continuous block of memory. 
- Lack vectorized operations, relying on loops instead.  
- Have significant overhead due to dynamic typing.

### NumPy’s Superpowers:
• Faster than Python lists (C-optimized backend)
• Uses less memory (efficient storage)
• Supports vectorized operations (no explicit loops needed)
• Has built-in mathematical functions


 

###Adding Two Lists vs. NumPy Arrays

In [9]:
#using python lists
import numpy as np
import time 

size = 1_000_000

l1 = list(range(size))
l2 = list(range(size))

start = time.time()
add = [x + y for x, y in zip(l1,l2)]
end = time.time()
print(end - start)

0.1038827896118164


In [10]:
#using Numpy arrays
import numpy as np
import time 

size = 1_000_000

l1 = np.array(list(range(size)))
l2 = np.array(list(range(size)))

start = time.time()
add = l1 + l2
end = time.time()
print(end - start)

0.015467405319213867


In [12]:
###NumPy is significantly faster because it performs operations in C,avoiding Python loops

In [13]:
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [16]:
print(np.array([[1, 2, 3], [4, 5, 6]]))

[[1 2 3]
 [4 5 6]]


In [25]:
arr=np.array([[1, 2, 3], [4, 5, 6]])
print(type(arr))
print(arr.shape)

<class 'numpy.ndarray'>
(2, 3)


###Summary
NumPy is faster than Python lists because it is optimized in C.
It consumes less memory due to efficient storage.
It provides vectorized operations, removing the need for slow loops.
Essential for data science and machine learning workflows.
